### ISSUE TITLE
Files linked to the main TOSCA yaml are not accessible to the orchestrator. 

### ISSUE THREAD

**Issue by cankarm** [radon-h2020/xopera-opera#1]
In the case of the CSAR-tree, the orchestrator ignores the referenced file defined in the main TOSCA yaml and returns a

[Path] Path <path to the file> does not exist.

type of error. The referenced file is in the same folder then the main file.

**Comment by cankarm** [comment]
Related to: xlab-si/xopera-opera/#25

**Comment by tadeboro** [comment]
This has been fixed in the upstream repo and the fixed version of opera has been released.

**Comment by cankarm** [comment]
Fixed with https://github.com/xlab-si/xopera-opera/pull/26
