### ISSUE TITLE
Adding credentials on xopera SaaS

### ISSUE THREAD

**Issue by gcasale** [radon-h2020/xopera-opera#16]
In xopera-saas, clicking on the "manage secrets" feature of the workspace, one may accidentally press "Assign secret" before choosing which secret from the dropdown. In this case the Assign secret button becomes forever pressed and one needs to close the window and redo.

**Comment by cankarm** [comment]
@sstanovnik - please triage this.

**Comment by sstanovnik** [comment]
Triaged into the front of the queue due to ease of resolution.

**Comment by sstanovnik** [comment]
The fix for this issue has just been deployed. Requesting close.

**Comment by cankarm** [comment]
Thanks @sstanovnik, it seems to work now.

**Comment by gcasale** [comment]
Approved
