### ISSUE TITLE
Availability of the Opera parsing functionality for TOSCA files as a (Python) library

### ISSUE THREAD

**Issue by duelle** [radon-h2020/xopera-opera#7]
As several partners need to parse TOSCA files to extract information, one idea would be to make the Opera parser available as a library.
From our (CTT) point of view it would be probably enough to have it available as a Python library and be able to get the information from the TOSCA files/structure in JSON, YAML, or Python dictionary.

As discussed in WP6
@chinmaya-dehury @stefanodallapalma @naesheim @cankarm

**Comment by stefanodallapalma** [comment]
HI @duelle, 

thank you. This is a very good point.
I like the idea of a Python library, it would facilitate the integration in the current tools.
As from my side, I link the [ToscaMetrics documentation](https://github.com/radon-h2020/ToscaMetrics/tree/master/docs/metrics). The list of metrics refer to structural properties of a TOSCA blueprint, for example, the [number of nodes](https://github.com/radon-h2020/ToscaMetrics/blob/master/docs/metrics/NUMBER_OF_NODES.md), the [number of relationships](https://github.com/radon-h2020/ToscaMetrics/blob/master/docs/metrics/NUMBER_OF_RELATIONSHIPTYPES.md), [capabilities](https://github.com/radon-h2020/ToscaMetrics/blob/master/docs/metrics/NUMBER_OF_GENERAL_CAPABILITIES.md) and more.
They are mainly "counters". 

I and a student that is working on it for a master thesis created our [tosca parser](https://github.com/radon-h2020/ToscaMetrics/tree/master/toscaparser) to support those metrics. Actually I do not remember what metrics require this "extended" version and what don't (I will ask the student for clarifications).
It would be nice to figure out what can be re-used from this parser and whether there is something that can be merged.

For example, what kind of information can be extracted with the Tosca parser implemented in XOpera?

**Comment by chinmaya-dehury** [comment]
For data pipeline plugin, we (UTR) as well need to have a TOSCA parser that will make some changes on the user’s CSAR file. For example, the parser would get the list of pipeline nodes, check the underlined instances (or VMs or hosts), If they are sharing same host. Based on this the relationship will be updated and will be sent to the orchestrator. 

So the input and the output to the data pipeline plugin would be the service template and the plugin (along with the parser) would analyze and process the service template.

**Comment by anzoman** [comment]
Hi all, in the past opera had the ability to just parse the supplied TOSCA service template without actually running the deployment. With  TOSCA YAML profile version 1.3 this was dropped due to compatibility issues.

But the future is bright because we resurrected this forgotten [opera validate command ](https://github.com/xlab-si/xopera-opera/commit/91b9fe4a3f96c0f42a8e5dd0da5b269da54aaa29) and this will be available for use with the new release. With this command opera will tell if the TOSCA service template and its dependencies are correct or it will warn the user in case there were some parsing problems.

@duelle will this make your use case easier?

**Comment by duelle** [comment]
Thanks for looking into this @anzoman,

for our use case, it would be more important to obtain the structure that is represented in the CSAR in a format we can use in Python. May it be YAML/JSON or even something that we can directly use in Python like a dictionary.
Our aim is to extract some properties/values from the service templates to parameterize tests configured through CTT.

The feature to have a validity check is still a nice thing to have I would say. Maybe as some kind of a pre-check before we try to deploy something via opera (especially once it is deployed as a SaaS solution).

**Comment by anzoman** [comment]
Hi,

@duelle opera already works in a way that it creates a directed graph with nodes so it is possible to retrieve them during execution.  For that one has to foray into opera's source code and add a little magic ;).

Here is the python script (`test.py`) I've prepared for parsing template and retrieving nodes and their values(attributes, properties, inputs):

```python
from pathlib import Path, PurePath
from opera.error import DataError, ParseError
from opera.parser import tosca
from sys import argv
from opera.storage import Storage


def parse():
    try:
        root_file = argv[1]
        storage = Storage(Path(".opera"))
        storage.write(root_file, "root_file")
        ast = tosca.load(Path.cwd(), PurePath(root_file))
        template = ast.get_template({})
        topology = template.instantiate(storage)

        nodes = topology.nodes
        node_keys = list(nodes.keys())
        node_values = list(nodes.values())
        print("Nodes: " + str(nodes))
        print("Node keys: " + str(node_keys))
        print("Node values: " + str(node_values))
        print()

        node_1_properties = node_values[1].template.properties
        node_1_properties_keys = list(node_1_properties.keys())
        test_property = node_1_properties['test_property'].data
        print("Node 1 properties: " + str(node_1_properties))
        print("Node 1 properties keys: " + str(node_1_properties_keys))
        print("Node 1 test property: " + str(test_property))
        print()

        node_1_attributes = node_values[1].template.attributes
        node_1_attributes_keys = list(node_1_attributes.keys())
        test_attribute = node_1_attributes['test_attribute'].data
        print("Node 1 attributes: " + str(node_1_attributes))
        print("Node 1 attributes keys: " + str(node_1_attributes_keys))
        print("Node 1 test attribute: " + str(test_attribute))
        print()

        inputs = template.inputs
        test_input_node = node_values[1].get_input('test_input')
        test_input_topology = inputs['test_input'].data
        print("Inputs: " + str(inputs))
        print("Node 1 test input: " + str(test_input_node))
        print("Node 1 test input: " + str(test_input_topology))

    except ParseError as e:
        print("{}: {}".format(e.loc, e))
        return 1
    except DataError as e:
        print(str(e))
        return 1


if __name__ == '__main__':
    parse()

``` 

Maybe it's somehow unclear but it is possible to import and use opera as a package in python. The part of the orchestrator code I'm mostly using here are opera [instances](https://github.com/xlab-si/xopera-opera/tree/master/src/opera/template) which mostly represent entities like nodes and relationships during orchestration. These actually form a graph-like structure that can be dismantled back to pieces by using some of their defined methods.

Here is `test.yml` TOSCA template I which used for testing:

```yaml
---
tosca_definitions_version: tosca_simple_yaml_1_3

node_types:
  hello_type:
    derived_from: tosca.nodes.SoftwareComponent
    properties:
      test_property:
        type: string
    attributes:
      test_attribute:
        type: integer
        default: 42
    interfaces:
      Standard:
        type: tosca.interfaces.node.lifecycle.Standard
        inputs:
          test_input:
            default: { get_input: test_input }
            type: float

topology_template:
  inputs:
    test_input:
      type: string
      default: 10.10

  node_templates:
    my-workstation:
      type: tosca.nodes.Compute
      attributes:
        private_address: localhost
        public_address: localhost

    hello:
      type: hello_type
      properties:
        test_property: testing123
      requirements:
        - host: my-workstation
...
```

You can see that I included property, atrribute and input which I will try to retrieve.
So when you run the script with `python3 test.py test.yml` you get the following output:

```console
anzoman@ubuntu:~/Desktop/xopera-opera$ python3 test.py test.yml
Nodes: {'my-workstation_0': <opera.instance.node.Node object at 0x7fd1249fb7f0>, 'hello_0': <opera.instance.node.Node object at 0x7fd1249fb6d8>}
Node keys: ['my-workstation_0', 'hello_0']
Node values: [<opera.instance.node.Node object at 0x7fd1249fb7f0>, <opera.instance.node.Node object at 0x7fd1249fb6d8>]

Node 1 properties: {'component_version': <opera.value.Value object at 0x7fd1249fbcf8>, 'admin_credential': <opera.value.Value object at 0x7fd1249fbc88>, 'test_property': <opera.value.Value object at 0x7fd1249fbc50>}
Node 1 properties keys: ['component_version', 'admin_credential', 'test_property']
Node 1 test property: testing123

Node 1 attributes: {'tosca_id': <opera.value.Value object at 0x7fd1249fbc18>, 'tosca_name': <opera.value.Value object at 0x7fd1249fbba8>, 'state': <opera.value.Value object at 0x7fd1249fbb70>, 'test_attribute': <opera.value.Value object at 0x7fd1249fbb38>}
Node 1 attributes keys: ['tosca_id', 'tosca_name', 'state', 'test_attribute']
Node 1 test attribute: 42

Inputs: {'test_input': <opera.value.Value object at 0x7fd1249fbfd0>}
Node 1 test input: 10.1
Node 1 test input: 10.1
```

The script extracts and prints out the desired values for the properties, attributes and inputs during the orchestration. So in this case you can can directly use those object in Python for your use cases. Would this be useful for you?

**Comment by cankarm** [comment]
Thanks @anzoman. This is probably useful also for @chinmaya-dehury and @pjakovits. Probably we could add these scripts and examples in particular repository, where it is possible to fork and improve them as needed.

**Comment by chinmaya-dehury** [comment]
That's a nice snippet for basic operations @anzoman .
We (UTR) have two approaches. 
Approach-1: to go with the common parser to most of the units/tools. 
Approach-2: to go with our own parser specifically developed for data pipeline plugin with only required features. 

For the time being, we are with Approach-2. But it would be nice to see a TOSCA parser at the end, which is highly matured and provides enough number of features for different purposes, such for modeller, orchestrator, pipeline plugin etc.

**Comment by chinmaya-dehury** [comment]
> Thanks @anzoman. This is probably useful also for @chinmaya-dehury and @pjakovits. Probably we could add these scripts and examples in particular repository, where it is possible to fork and improve them as needed.

Yes @cankarm , that's possible and could be a good way to have a common parser for other tools.
As alternate, we may also fork the parser module of other tools (ofcourse if the concern tool owner agrees) and develop to matured independent parser with the contributions from other unit members.

**Comment by anzoman** [comment]
@cankarm opera CLI is available to be used within python scripts so this issue may not be relevant anymore. For the future we should document the opera CLI code with python docstrings and use them within opera documentation to explain how opera can be used within python scripts.

**Comment by cankarm** [comment]
Ok, I'm closing this for now.
