### ISSUE TITLE
Exposure of (un)deployment "sub-steps" via CLI/API (Feature Request)

### ISSUE THREAD

**Issue by duelle** [radon-h2020/xopera-opera#8]
In order to control the steps inside the `deploy` and `undeploy` of opera, it would be a nice feature if one could trigger the Standard operations `create`, `configure`, `start`, `stop`, `delete` defined in TOSCA individually.

Initial ideas:
This could be exposed either via their own commands:
`opera {deploy|undeploy|create|configure|start|stop|delete} ..` 
or as (optional) sub-commands:
`opera deploy --subcmd {create|configure|start}`
`opera deploy --subcmd {stop|delete}`

The respective commands would then only call the specific parts defined in the standard operations.

For us, this would be interesting, as we have internal steps for deploying, configuring, and executing, which we could map to the standard operations if we could trigger them individually.

**Comment by anzoman** [comment]
Hi @duelle sorry for a little late response but yes I see that this could be a really nice feature. 

Currently if you call xOpera orchestrator  with `opera deploy` command it invokes the following TOSCA Standard interface node operations (from `tosca.interfaces.node.lifecycle.Standard`) and also TOSCA Configure interface relationship operations (from `tosca.interfaces.relationship.Configure`):

1. create
2. pre_configure_source
3. pre_configure_target
4. configure
5. post_configure_source
6. post_configure_target
7. start

When called with `opera undeploy` the following occurs:

1. stop
2. delete

So I will have a look and propose this to be updated and will keep you posted here.

**Comment by anzoman** [comment]
@cankarm this issue is further explained here: https://github.com/xlab-si/xopera-opera/issues/62. I think that we can close this one and keep only the one from upstream.

**Comment by cankarm** [comment]
Ok, I agree.
