### ISSUE TITLE
Installing using README.md getting start

### ISSUE THREAD

**Issue by gcasale** [radon-h2020/xopera-opera#9]
The README.md example worked fine for me, some minor problems to fix:
- at no point README.md says when to clone the git repo and cd into the folder
- after verifying that hello.txt exists it is not clear what to do to continue and how to use the tool to do something more substantial like start a VM or container somewhere.

**Comment by anzoman** [comment]
Hi, thanks for opening this issue. 

So considering your minor problems: `README.md` doesn't say to clone the xopera's git repository explicitly but this the only logical thing you should to if you wanna test the examples that reside there. And for the second part I agree that hello world example definitely needs polishing. 

So yes xOpera's `README.md` currently does not provide detailed instructions and examples. But we are working on that and recently we established a microsite with xOpera documentation that describes installation and usage of this TOSCA orchestrator thoroughly and in a more user-friendly way that its README. In the future we aim provide even more examples and to describe the parser and its usage in detail.

So I suggest that you take a look at opera's documentation here: https://xlab-si.github.io/xopera-docs/ and if you have any questions feel free to reach out again here.

**Comment by gcasale** [comment]
This is a 5 minutes change, can we apply it to the README?

**Comment by anzoman** [comment]
Yes of course we can add the info about cloning the repository to test the examples and the suggestion to look at the docs. @cankarm should we apply this only here in this fork because (that way it will be take like 5 minutes) or also within the PR to the main opera repo?

**Comment by anzoman** [comment]
This has been resolved and the latest opera README includes the info about cloning the opera's repository before trying to deploy the examples within. Therefore I propose closing this.

**Comment by gcasale** [comment]
Thanks. This point is still open: "at no point README.md says when to clone the git repo and cd into the folder"

**Comment by cankarm** [comment]
Correct, @anzoman updated readme in the upstream xopera version, but the fork in /radon-h2020 organisation was still behind. Now I merged all commits to this fork and everything should be OK.

**Comment by gcasale** [comment]
Yes I see it, thanks!
